# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build corne nice_nano_v2'
on: workflow_dispatch
jobs:
  build_left:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left"]'
      snippet: '["studio-rpc-usb-uart"]'
      kconfig: '["CONFIG_ZMK_PM_SOFT_OFF=y","CONFIG_ZMK_STUDIO=y"]'
      alphas: '["QWERTY"]'

  build_right:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_right"]'
      kconfig: '["CONFIG_ZMK_PM_SOFT_OFF=y","CONFIG_ZMK_STUDIO=y"]'
      alphas: '["QWERTY"]'
